version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: DockerfileDev
        image: authors-api
        container_name: authors-api
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
    webserver:
        image: nginx:1.23.3-alpine
        container_name: server_nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
            - ./nginx:/etc/nginx/conf.d
