version: '3.8'
services:
    lumen:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: lumen
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
